[workspace]
members = [
  "dist",
  "metas/memory",
  "networks/tonic",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/systemxlabs/datafusion-dist"
license = "MIT"
repository = "https://github.com/systemxlabs/datafusion-dist"

[workspace.dependencies]
async-trait = "0.1"
datafusion = "50"
futures = "0.3"
