[workspace]
members = [
  "dist",
  "clusters/memory",
  "clusters/postgres",
  "networks/tonic",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/systemxlabs/datafusion-dist"
license = "MIT"
repository = "https://github.com/systemxlabs/datafusion-dist"

[workspace.dependencies]
async-trait = "0.1"
datafusion = "50"
futures = "0.3"
serde = "1.0"
sysinfo = "0.37"
tokio = "1"
uuid = { version = "1.18" }