[package]
name = "datafusion-dist-network-tonic-gen"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
description = "Code generation for proto"
publish = false

[dependencies]
tonic-prost-build = { workspace = true }